export const GET_LIMIT_WATCH_HISTORY = "GET_LIMIT_WATCH_HISTORY";
export const GET_LIMIT_WATCH_HISTORY_SUCCESS = "GET_LIMIT_WATCH_HISTORY_SUCCESS";
export const GET_LIMIT_WATCH_HISTORY_FAILURE = "GET_LIMIT_WATCH_HISTORY_FAILURE";

export const CREATE_WATCH_HISTORY = "CREATE_WATCH_HISTORY";
export const CREATE_WATCH_HISTORY_SUCCESS = "CREATE_WATCH_HISTORY_SUCCESS";
