// for collection constant in dashboard 

export const GET_ALL_COLLECTION_NAME = "GET_ALL_COLLECTION_NAME";
export const GET_LIMIT_COLLECTION_NAME = "GET_LIMIT_COLLECTION_NAME";
export const EDIT_COLLECTION_NAME = "EDIT_COLLECTION_NAME";
export const CREATE_COLLECTION_NAME = "CREATE_COLLECTION_NAME";

export const GET_ALL_COLLECTION_NAME_SUCCESS = "GET_ALL_COLLECTION_NAME_SUCCESS";
export const GET_LIMIT_COLLECTION_NAME_SUCCESS = "GET_LIMIT_COLLECTION_NAME_SUCCESS";
export const EDIT_COLLECTION_NAME_SUCCESS = "EDIT_COLLECTION_NAME_SUCCESS";
export const CREATE_COLLECTION_NAME_SUCCES = "CREATE_COLLECTION_NAME_SUCCES";

export const GET_ALL_COLLECTION_NAME_FAILURE = "GET_ALL_COLLECTION_NAME_FAILURE";
export const GET_LIMIT_COLLECTION_NAME_FAILURE = "GET_LIMIT_COLLECTION_NAME_FAILURE";
export const EDIT_COLLECTION_NAME_FAILURE = "EDIT_COLLECTION_NAME_FAILURE";
export const CREATE_COLLECTION_NAME_FAILURE = "CREATE_COLLECTION_NAME_FAILURE";
