export const GET_SPECIFIC_COLLECTION_ITEM = "GET_SPECIFIC_COLLECTION_ITEM";
export const GET_SPECIFIC_COLLECTION_ITEM_SUCCESS = "GET_SPECIFIC_COLLECTION_ITEM_SUCCESS";
export const GET_SPECIFIC_COLLECTION_ITEM_FAILURE = "GET_SPECIFIC_COLLECTION_ITEM_FAILURE";

export const CREATE_MEDIA = "CREATE_MEDIA";
export const EDIT_MEDIA = "EDIT_MEDIA";
export const DELETE_MEDIA = "DELETE_MEDIA";
export const MOVE_MEDIA = "MOVE_MEDIA";


export const CREATE_MEDIA_SUCCESS = "CREATE_MEDIA_SUCCESS";
export const EDIT_MEDIA_SUCCESS = "EDIT_MEDIA_SUCCESS";
export const DELETE_MEDIA_SUCCESS = "DELETE_MEDIA_SUCCESS";
export const MOVE_MEDIA_SUCCESS = "MOVE_MEDIA_SUCCESS";


export const ERROR_IN_MEDIA = "ERROR_IN_MEDIA";